spring:
  application:
    name: stocks-be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  cloud:
    aws:
      s3:
        bucket-name: ${AWS_S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}